packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^4.16.1
    '@antfu/ni': ^25.0.0
    bumpp: ^10.2.0
    eslint: ^9.29.0
    lint-staged: ^16.1.2
    pnpm: ^10.12.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tsdown: ^0.12.8
    tsx: ^4.20.3
    typescript: ^5.8.3
    vite: ^6.3.5

  inlined:
    '@antfu/utils': ^9.2.0

  play:
    unimport: ^5.0.1
    vue: ^3.5.17
    vue-router: ^4.5.1

  prod:
    '@typescript-eslint/scope-manager': ^8.34.1
    '@typescript-eslint/utils': ^8.34.1
    debug: ^4.4.1
    html-tags: ^5.0.0
    pathe: ^2.0.3

  testing:
    vitest: ^3.2.4

  types:
    '@types/debug': ^4.1.12
    '@types/node': ^24.0.3
